services:
  # Backend API Server
  - type: web
    name: arbitrage-bot-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/api-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PROVIDER_URL
        value: https://arb1.arbitrum.io/rpc
